#
#
# Processes to launch from niryo_one_rpi node
# (don't put circular dependencies)
#

processes:
    - name: 'controllers'
      launch_on_startup: true
      delay_before_start: 0.0
      cmd: 'roslaunch niryo_one_bringup controllers.launch'
      args:
          []
      dependencies:
          []
